-- 为客服账号添加更多个人信息字段
ALTER TABLE `admin` ADD COLUMN IF NOT EXISTS `email` VARCHAR(100) DEFAULT '' COMMENT '邮箱' AFTER `avatar`;
ALTER TABLE `admin` ADD COLUMN IF NOT EXISTS `phone` VARCHAR(20) DEFAULT '' COMMENT '手机号' AFTER `email`;
ALTER TABLE `admin` ADD COLUMN IF NOT EXISTS `wechat` VARCHAR(50) DEFAULT '' COMMENT '微信号' AFTER `phone`;
ALTER TABLE `admin` ADD COLUMN IF NOT EXISTS `signature` VARCHAR(200) DEFAULT '' COMMENT '个人签名' AFTER `wechat`;
ALTER TABLE `admin` ADD COLUMN IF NOT EXISTS `status` TINYINT DEFAULT 1 COMMENT '在线状态：0离线 1在线' AFTER `signature`;
